#!/bin/bash

# Telegram RSS Bot - Interactive Setup Script
# This script helps you configure the bot quickly

set -e

echo "=================================="
echo "  Telegram RSS Bot Setup"
echo "=================================="
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
    mv .env .env.backup
    echo "✅ Existing .env backed up to .env.backup"
fi

# Create .env file
echo "Let's configure your bot..."
echo ""

# Telegram Token
echo "1️⃣  Telegram Bot Configuration"
echo "   Get your bot token from @BotFather on Telegram"
read -p "   Enter your bot token: " TELEGRAM_TOKEN
echo ""

# Chat ID
echo "2️⃣  Channel Configuration"
echo "   Enter your channel username (e.g., @mynewschannel)"
echo "   Or numeric chat ID (e.g., -1001234567890)"
read -p "   Enter channel ID: " CHAT_ID
echo ""

# RSS Feed
echo "3️⃣  RSS Feed"
read -p "   Enter RSS feed URL [https://24.hu/feed/]: " RSS_URL
RSS_URL=${RSS_URL:-https://24.hu/feed/}
echo ""

# Translator
echo "4️⃣  Translation Engine"
echo "   Available options:"
echo "   1) google (FREE, basic quality)"
echo "   2) mymemory (FREE, alternative)"
echo "   3) libretranslate (FREE, open source)"
echo "   4) deepl (FREE tier, best quality)"
echo "   5) openai (PAID, ChatGPT)"
echo "   6) anthropic (PAID, Claude)"
read -p "   Choose translator [1-6, default: 1]: " TRANSLATOR_CHOICE
TRANSLATOR_CHOICE=${TRANSLATOR_CHOICE:-1}

case $TRANSLATOR_CHOICE in
    1) TRANSLATOR_TYPE="google" ;;
    2) TRANSLATOR_TYPE="mymemory" ;;
    3) TRANSLATOR_TYPE="libretranslate" ;;
    4) TRANSLATOR_TYPE="deepl" ;;
    5) TRANSLATOR_TYPE="openai" ;;
    6) TRANSLATOR_TYPE="anthropic" ;;
    *) TRANSLATOR_TYPE="google" ;;
esac
echo ""

# API Keys for paid services
DEEPL_API_KEY=""
OPENAI_API_KEY=""
OPENAI_MODEL="gpt-4o-mini"
ANTHROPIC_API_KEY=""
ANTHROPIC_MODEL="claude-3-5-haiku-20241022"

if [ "$TRANSLATOR_TYPE" = "deepl" ]; then
    echo "   DeepL API Key"
    echo "   Get it at: https://www.deepl.com/pro-api"
    read -p "   Enter DeepL API key: " DEEPL_API_KEY
    echo ""
elif [ "$TRANSLATOR_TYPE" = "openai" ]; then
    echo "   OpenAI API Key"
    echo "   Get it at: https://platform.openai.com/api-keys"
    read -p "   Enter OpenAI API key: " OPENAI_API_KEY
    read -p "   Enter model [gpt-4o-mini]: " MODEL_INPUT
    OPENAI_MODEL=${MODEL_INPUT:-gpt-4o-mini}
    echo ""
elif [ "$TRANSLATOR_TYPE" = "anthropic" ]; then
    echo "   Anthropic API Key"
    echo "   Get it at: https://console.anthropic.com/"
    read -p "   Enter Anthropic API key: " ANTHROPIC_API_KEY
    read -p "   Enter model [claude-3-5-haiku-20241022]: " MODEL_INPUT
    ANTHROPIC_MODEL=${MODEL_INPUT:-claude-3-5-haiku-20241022}
    echo ""
fi

# Languages
echo "5️⃣  Languages"
read -p "   Source language code [hu]: " SOURCE_LANGUAGE
SOURCE_LANGUAGE=${SOURCE_LANGUAGE:-hu}
read -p "   Target language code [ru]: " TARGET_LANGUAGE
TARGET_LANGUAGE=${TARGET_LANGUAGE:-ru}
echo ""

# Check interval
echo "6️⃣  Check Interval"
read -p "   How often to check feed (seconds) [300]: " CHECK_INTERVAL
CHECK_INTERVAL=${CHECK_INTERVAL:-300}
echo ""

# Write .env file
cat > .env << EOF
# Telegram RSS Bot Configuration
# Generated by setup.sh on $(date)

# Telegram Settings
export TELEGRAM_TOKEN="$TELEGRAM_TOKEN"
export CHAT_ID="$CHAT_ID"

# RSS Feed
export RSS_URL="$RSS_URL"

# Translation
export TRANSLATOR_TYPE="$TRANSLATOR_TYPE"
export SOURCE_LANGUAGE="$SOURCE_LANGUAGE"
export TARGET_LANGUAGE="$TARGET_LANGUAGE"

# API Keys
export DEEPL_API_KEY="$DEEPL_API_KEY"
export OPENAI_API_KEY="$OPENAI_API_KEY"
export OPENAI_MODEL="$OPENAI_MODEL"
export ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
export ANTHROPIC_MODEL="$ANTHROPIC_MODEL"

# Bot Settings
export CHECK_INTERVAL="$CHECK_INTERVAL"
export MAX_DESCRIPTION_LENGTH="500"
export MAX_CONTENT_LENGTH="5000"
export LOG_LEVEL="INFO"
EOF

echo "✅ Configuration saved to .env"
echo ""

# Test dependencies
echo "7️⃣  Checking Dependencies..."
echo ""

if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is not installed"
    exit 1
fi

echo "✅ Python 3 found: $(python3 --version)"

# Check if requirements are installed
if ! python3 -c "import telegram" 2>/dev/null; then
    echo "⚠️  Dependencies not installed"
    read -p "   Install now? (Y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        echo "   Installing dependencies..."
        pip3 install -r requirements.txt
        echo "✅ Dependencies installed"
    fi
else
    echo "✅ Dependencies already installed"
fi

echo ""
echo "=================================="
echo "  Setup Complete! 🎉"
echo "=================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Test your bot:"
echo "   source .env && python3 rss_bot.py --once"
echo ""
echo "2. Run the bot:"
echo "   source .env && python3 rss_bot.py"
echo ""
echo "3. Or set up as daemon:"
echo "   See README.md for systemd/Docker setup"
echo ""
echo "Configuration file: .env"
echo "Edit anytime with: nano .env"
echo ""
